version: '3.8'

services:
  home:
    build:
      context: .
      dockerfile: apps/home/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DASHBOARD_URL=http://dashboard:3001
      - LOGIN_URL=http://login:3002
    networks:
      - app-network
    depends_on:
      - dashboard
      - login
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - HOME_URL=http://home:3000
      - LOGIN_URL=http://login:3002
    networks:
      - app-network
    depends_on:
      - login
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 3

  login:
    build:
      context: .
      dockerfile: apps/login/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - HOME_URL=http://home:3000
      - DASHBOARD_URL=http://dashboard:3001
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3002"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge